In [1]:
import numpy as np

In [2]:
# как создать матрицу?

In [3]:
# как двумерный массив Numpy
np.array( [ [1,1] , [2,3] , [4,5] ] )

array([[1, 1],
       [2, 3],
       [4, 5]])

In [4]:
# преобразовать из Pandas DataFrame
import pandas as pd

data=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
df = pd.DataFrame(data)

A = df.values

print('Data Frame:')
print(df)
print('Matrix:')
print(A)

Data Frame:
    0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# размер матрицы
np.shape(A)

(4, 3)

In [6]:
# вектор-столбец
x=np.array([1,2,3])
np.reshape(x,(3,1))

array([[1],
       [2],
       [3]])

In [ ]:
# вектор-строка
np.reshape(x,(1,3))

In [ ]:
# вектор-строка
x_row=np.array([1, 2, 3], ndmin=2)
print(x_row,np.shape(x_row))

In [ ]:
# индексация матриц (двумерных массивов numpy)
print('матрица А:')
print(A)
print('Первая строка матрицы А:')
print(A[0])
print('Третий столбец матрицы А:')
print(A[:,2])
print('Элемент а_43:')
print(A[3,2])

In [ ]:
# создание специальных матриц

In [ ]:
# нулевая
np.zeros((2,3))

In [ ]:
# единичная
np.eye(3)

In [ ]:
# матрица единиц
np.ones((3,5))

In [ ]:
# Диагональная
diagonal=[1,2,3]
np.diag(diagonal)

In [ ]:
# Шаровая
5*np.eye(3)

In [ ]:
A=np.array([[1,1],[2,3],[4,5]])
B=np.array([[1,-1],[-2,3],[4,-5]])

In [ ]:
A

In [ ]:
B

In [ ]:
A+B

In [ ]:
B+A

In [ ]:
A-B

In [ ]:
2*A

In [ ]:
A.T

In [ ]:
# как транспонировать вектор?
x=np.array([1,2,3])
x.T

In [ ]:
x_col=np.reshape(x,(3,1))
print(x_col)
print(np.shape(x_col))

In [ ]:
x_col.T

In [ ]:
print(np.shape(x))
print(np.shape(x_col))
print(np.shape(x_col.T))