
# PYTHON-9. Возможности библиотеки Numpy для работы с данными


In [267]:

import numpy as np
from IPython.core.display import display

arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [268]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype


dtype('float64')

In [269]:

arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)


(3, 3)

In [270]:
import numpy as np
import pandas as pd

df = pd.DataFrame()
x = df.values

type(x)

numpy.ndarray

In [271]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values


array([ 5,  6,  7,  8,  9, 10])

In [272]:
# одномерный массив из пяти элементов,
# память для которого выделена, но не инициализирована
np.empty(5)

# массив размером 10x7, заполненный нулями
np.zeros((10, 7))

# массив размером 3х3х3, заполненный единицами
np.ones((3,3,3))

# единичная матрица (элементы главной диагонали равны 1, остальные — 0)
# размера 3х3
np.eye(3)

# массив 3x5 заполненный числом 3.14
np.full((3, 5), 3.14)

# одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7
np.arange(0, 21, 7)

# массив из пяти чисел, равномерно распределённых
# в интервале между 0 и 1 включительно
np.linspace(0, 1, 5)

# массив размера 3х3, заполненный случайными числами
# из диапазона от 0 до 9 (включительно)
np.random.randint(0, 10, (3, 3))


array([[7, 5, 6],
       [6, 7, 3],
       [0, 0, 7]])

In [273]:
# Какой индекс имеет верхний левый элемент любого двумерного массива?
m = np.random.randint(0, 9, (3,3))
display(m)
m[0][0]


array([[1, 3, 8],
       [3, 0, 3],
       [1, 0, 2]])

1

In [274]:

# Какие элементы расположены на главной диагонали массива, заданного с помощью кода выше?
data = [[8,13,18,4], [25,3,18,28], [14,15,18,24], [1,2,3,4]]
m = np.array(data)
display(m)

array([[ 8, 13, 18,  4],
       [25,  3, 18, 28],
       [14, 15, 18, 24],
       [ 1,  2,  3,  4]])

In [275]:

# Какие элементы расположены в последнем столбце массива, заданного с помощью кода выше?
# my_secret = [x for x in range(1, 301, 7)]
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
res = np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])
display(res)


array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [276]:

# С помощью каких вариантов кода можно создать массив,
# среднее арифметическое всех элементов главной диагонали которого равно 1?
display(
    np.ones((5, 5)),
    np.eye(5),
    np.full((5,5), 1),
    np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])
)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [277]:
# С помощью каких вариантов кода НЕВОЗМОЖНО создать массив,
# представленный в примере выше?

m = np.array([
 [1, 1, 1],
 [0, 2, 2],
 [2, 4, 1]
])
display(
    m,
    np.random.randint(0, 4, (3, 3)),
    np.random.randint(0, 5, 3)
)

array([[1, 1, 1],
       [0, 2, 2],
       [2, 4, 1]])

array([[1, 0, 0],
       [3, 1, 1],
       [3, 3, 3]])

array([2, 3, 2])

In [278]:

# Какие из представленных вариантов кода можно использовать для создания массива 4х4,
# полностью заполненного единицами?

display(
    np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]),
    np.ones((4, 4), dtype=float),
    np.full((4, 4), 1)
    )



array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [279]:

# Какие из вариантов кода можно использовать для создания массива,
# заполненного нечётными числами?
display(
    np.ones((2,2,2)),
    np.array([i for i in range(11) if i%2]),
    np.arange(1, 14, 2)
    )




array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

array([1, 3, 5, 7, 9])

array([ 1,  3,  5,  7,  9, 11, 13])

In [280]:
my_array = np.array([x for x in range(10)])
display(
my_array,
my_array[1]
)



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1

In [281]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

display(
    first_line,
    '-' * 30,
    second_line,
    '-' * 30,
    third_line,
    '-' * 30,
    big_secret,
    big_secret[0][0],
    )



[14,
 10,
 6,
 56,
 40,
 24,
 98,
 70,
 42,
 140,
 100,
 60,
 182,
 130,
 78,
 224,
 160,
 96,
 266,
 190,
 114,
 308,
 220,
 132,
 350,
 250,
 150,
 392,
 280,
 168,
 434,
 310,
 186,
 476,
 340,
 204,
 518,
 370,
 222,
 560,
 400,
 240,
 602,
 430,
 258,
 644,
 460,
 276,
 686,
 490,
 294]

'------------------------------'

[31.622776601683793,
 31.654383582688826,
 31.68595903550972,
 31.71750305430741,
 31.74901573277509,
 31.78049716414141,
 31.811947441173732,
 31.843366656181317,
 31.874754901018456,
 31.906112267087632,
 31.937438845342623,
 31.96873472629156,
 32.0,
 32.03123475609393,
 32.0624390837628,
 32.09361307176243,
 32.12475680841802,
 32.155870381627054,
 32.18695387886216,
 32.218007387174026,
 32.2490309931942,
 32.28002478313795,
 32.31098884280702,
 32.341923257592455,
 32.37282811247729,
 32.4037034920393,
 32.43454948045371,
 32.46536616149585,
 32.49615361854384,
 32.526911934581186,
 32.55764119219941,
 32.58834147360065,
 32.61901286060018,
 32.64965543462902,
 32.68026927673638,
 32.71085446759225,
 32.7414110874898,
 32.77193921634788,
 32.802438933713454,
 32.83291031876401,
 32.863353450309965,
 32.89376840679705,
 32.92415526630866,
 32.95451410656816,
 32.984845004941285,
 33.015148038438355,
 33.04542328371661,
 33.075670817082454,
 33.1058907144937,
 33.13608305156178,
 3

'------------------------------'

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500]

'------------------------------'

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

14.0

In [282]:
# Чему равна сумма элементов последнего столбца массива?
# Ответ округлите до двух цифр после запятой:

round(sum(row[-1] for row in big_secret), 2)


3154.33

In [283]:

# Выделите из каждой строки массива big_secret первые 5 элементов.
# Чему равна сумма элементов главной диагонали получившейся матрицы?
# Округлите ответ до двух цифр после запятой

# ВАРИАНТ 1
new_matrix = np.array(
    [row[:6] for row in big_secret]
)

i = 0
diagonal = []
for row in new_matrix:
    diagonal.append(row[i])
    i+=1

display(round(sum(diagonal), 2))
# round(sum(diagonal)/len(diagonal), 2)


# ВАРИАНТ 2
matrix = big_secret[:5, :5]
display(matrix.astype(float))
round(sum(matrix[i][i] for i in range(5)), 2)



121.37

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

121.37

In [284]:

# Выделите из каждой строке массива big-secret
# первые пять элементов. Чему равна сумма элементов главной диагонали получившейся
# матрицы ответ округлите до двух цифр после запятой

# ВАРИАНТ 1
from functools import reduce


matrix = big_secret[:, -5:]
display(matrix.astype(int))

display(reduce(
    lambda x, y: x*y,
    [matrix[i][i] for i in range(5)]
))


# ВАРИАНТ 2
from functools import reduce
import numpy as np

display(
    reduce(np.multiply, np.diagonal(big_secret[:, -5:]))
)


array([[ 460,  276,  686,  490,  294],
       [  33,   33,   33,   33,   33],
       [2116, 2209, 2304, 2401, 2500],
       [  33,   33,   33,   33,   33],
       [ 460,  276,  686,  490,  294]])

341505315559.2347

341505315559.2347

In [285]:

my_array = np.random.randint(1, 100, (4, 6))
display(my_array)
my_slice = my_array[1:3, 2:4]
display(my_slice)

my_slice[:] = 0
display(my_array)
display(my_slice)


array([[46, 84, 92, 10,  2, 45],
       [54, 35, 67, 26, 30, 45],
       [52, 73, 74, 70, 15,  5],
       [85, 33, 45, 33, 15, 61]])

array([[67, 26],
       [74, 70]])

array([[46, 84, 92, 10,  2, 45],
       [54, 35,  0,  0, 30, 45],
       [52, 73,  0,  0, 15,  5],
       [85, 33, 45, 33, 15, 61]])

array([[0, 0],
       [0, 0]])

In [286]:

# Проверим знания! Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса
# нечётные, и на -1 все элементы, у которых оба индекса чётные.
big_secret[:, ::2] = -1
big_secret[:, 1::2] = 1
big_secret.astype(int)


array([[-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1],
       [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1],
       [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1],
       [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
        -1,  1, -1],
       [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1, 

In [287]:

# Выделите из каждой строке обновлённого массива Биг секрет первые пять элементов. Чему равна сумма элементов главной
# диагонали получившийся матрицы!? Видите полученный ответ без изменений и округлений.

np.sum(np.diagonal(big_secret[:, :5]))



-1.0

In [288]:
# Выделите из каждой строке обновлённого насиба Биг secret последние пять элементов. Чему равно произведение элементов
# главной диагонали получившиеся матрицы воскли? Видите полученный результат без изменений и округлений.

reduce(np.multiply, np.diagonal(big_secret[:, :-5]))



-1.0

In [289]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print(
    'Сумма: {}\nРазность: {}\nПроизведение: '
    '{}\nЧастное: {}\nУмножение на число: {}'
    ''.format(
        result1, result2, result3, result4, result5))


Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [290]:

my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [291]:
my_array = np.random.randint(0, 10, 20)
display(my_array)
my_array.reshape((4,5))


array([7, 6, 4, 8, 9, 0, 6, 6, 7, 4, 4, 9, 9, 3, 8, 1, 1, 8, 5, 7])

array([[7, 6, 4, 8, 9],
       [0, 6, 6, 7, 4],
       [4, 9, 9, 3, 8],
       [1, 1, 8, 5, 7]])

In [292]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])
display(my_array)
my_array.flatten()



array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [293]:
my_array = np.random.randint(0, 10, (3,4))
display(
    my_array,
    my_array<5,
    my_array[my_array<5],
)


array([[8, 1, 7, 1],
       [5, 4, 1, 5],
       [7, 0, 1, 5]])

array([[False,  True, False,  True],
       [False,  True,  True, False],
       [False,  True,  True, False]])

array([1, 1, 4, 1, 0, 1])

In [294]:

mask = np.array([1, 0, 1, 0], dtype=bool)
display(mask, my_array)

my_array[:, mask]



array([ True, False,  True, False])

array([[8, 1, 7, 1],
       [5, 4, 1, 5],
       [7, 0, 1, 5]])

array([[8, 7],
       [5, 1],
       [7, 1]])

In [295]:
my_array = np.random.randint(0, 10, (4, 6))
display(
    my_array,
    np.sort(my_array, axis=1),
    np.sort(my_array, axis=0)
)


array([[0, 8, 3, 8, 7, 4],
       [9, 5, 3, 6, 9, 7],
       [2, 2, 3, 8, 1, 1],
       [3, 4, 1, 0, 5, 8]])

array([[0, 3, 4, 7, 8, 8],
       [3, 5, 6, 7, 9, 9],
       [1, 1, 2, 2, 3, 8],
       [0, 1, 3, 4, 5, 8]])

array([[0, 2, 1, 0, 1, 1],
       [2, 4, 3, 6, 5, 4],
       [3, 5, 3, 8, 7, 7],
       [9, 8, 3, 8, 9, 8]])

In [296]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T
great_secret.astype(int)


array([[ 0,  4, 66],
       [ 1,  4, 40],
       [ 1,  4, 67],
       [ 1,  4, 40],
       [ 2,  4, 68],
       [ 2,  4, 40],
       [ 2,  4, 68],
       [ 2,  4, 41],
       [ 2,  4, 69],
       [ 3,  4, 41],
       [ 3,  4, 70],
       [ 3,  4, 42],
       [ 3,  4, 70],
       [ 3,  4, 42],
       [ 3,  4, 71],
       [ 3,  4, 42],
       [ 4,  4, 72],
       [ 4,  4, 43],
       [ 4,  4, 72],
       [ 4,  4, 43],
       [ 4,  4, 73],
       [ 4,  4, 44],
       [ 4,  4, 74],
       [ 4,  4, 44],
       [ 4,  4, 74],
       [ 5,  4, 44],
       [ 5,  5, 75],
       [ 5,  5, 45],
       [ 5,  5, 76],
       [ 5,  5, 45],
       [ 5,  5, 76],
       [ 5,  5, 46],
       [ 5,  5, 77],
       [ 5,  5, 46],
       [ 5,  5, 78],
       [ 5,  5, 46],
       [ 6,  5, 78],
       [ 6,  5, 47],
       [ 6,  5, 79],
       [ 6,  5, 47],
       [ 6,  5, 80],
       [ 6,  5, 48],
       [ 6,  5, 80],
       [ 6,  5, 48],
       [ 6,  5, 81],
       [ 6,  5, 48],
       [ 6,  5, 82],
       [ 6,  

In [297]:

# Сколько столбцов содержит массив Грит секрет
np.shape(great_secret)


(100, 3)

In [298]:
# Чему равна сумма косинус of элементов первой строке массива грудь секрет
# ответ округлите до двух знаков после запитую

round(np.sum(np.cos(great_secret[0, :])), 2)

0.16

In [299]:

# Чему равна сумма элементов массива Греция Крит, значение которых больше 50
np.sum(great_secret[great_secret>50])


5470.0

In [300]:
# Переведите массив Греция Крит в одномерную форму.
# Какое значение в получившимся массиве имеет элемент с индексом 150?
# Скопируйте ответ из Jupiter ноутбук без изменений

# great_secret.flatten()[150]


In [323]:

# Отсортируйте значение столбцов массива крыть sacred по возрастанию. Чему равна сумма элементов последней строке
# отсортированного массива? Ответ округлите до двух цифр после запитую.
great_secret = np.array([first, second, third]).T
round(np.sum(np.sort(great_secret, axis=0)[-1, :]), 2)


115.12

In [326]:
students = np.array([
    [1,135,34,4],
    [2,160,43,5],
    [3,163,40,4.3],
    [4,147,44,5],
    [5,138,41,4.7],
    [6,149,54,3.9],
    [7,136,39,4.2],
    [8,154,48,4.9],
    [9,137,35,3.7],
    [10,165,60,4.6],
])
students.astype(int)

array([[  1, 135,  34,   4],
       [  2, 160,  43,   5],
       [  3, 163,  40,   4],
       [  4, 147,  44,   5],
       [  5, 138,  41,   4],
       [  6, 149,  54,   3],
       [  7, 136,  39,   4],
       [  8, 154,  48,   4],
       [  9, 137,  35,   3],
       [ 10, 165,  60,   4]])

In [327]:

mean = np.mean(students[:,-1])
mean


4.430000000000001

In [329]:
median = np.median(students[:,-1])
display(median)

sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2


4.449999999999999

4.449999999999999

In [331]:
# Чему равно медианное значение массы тела Школьников?

np.median(students[:, 2])


42.0

In [333]:
# Насколько среднее арифметическое массы тела Школьников больше медианного значение для этого же показателя? Дайте
# ответ в килограммах с точностью до одной десятой килограмма

round(np.median(students[:, 2]) - np.mean(students[:, 2]), 1)


-1.8

In [334]:

corr = np.corrcoef(students[:, 1], students[:, 2])
corr


array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

In [342]:
np.minimum(
    np.corrcoef(students[:, 1], students[:, 2]),
    np.corrcoef(students[:, 1], students[:, -1]),
    np.corrcoef(students[:, 2], students[:, -1])
)

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [343]:
std = np.std(students[:,1])
std

11.083320801997928

In [344]:

# Используя имеющиеся набор данных о школьниках найдите чему равно стандартно отклонение их средних баллов
std = np.std(students[:,-1])
std


0.4517742799230607

In [350]:
# Посчитайте, чему равна дисперсия значений веса школьников.
# Эту величину можно получить двумя способами:
# математически - используя определение дисперсии и известную функцию в блоке,
# или самостоятельно - используя подходящую функцию модуля NumPy.

# Вариант 1
std = np.std(students[:, 2])
display(std)
D = std ** 2
D

7.769169839822013

60.36

In [349]:
# Вариант 2
np.var(students[:, 2])

60.36

In [352]:
# Вариант 3
mean = np.sum(students[:, 2]) / len(students[:, 2])
var_res = (
    sum(
        [(xi - mean) ** 2 for xi in students[:, 2]]
    ) / len(students[:, 2])
)
var_res


60.36

In [354]:
np.ones((5,10), dtype = int)
np.full((10, 5), 1)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [358]:

#Перед вами массив my_array, созданный с помощью кода выше. Напишите код, с помощью которого можно извлечь из него
# центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

# Код должен содержать имя массива и набор индексов для получения нужного среза. В ответе использовать только
# положительные значения индексов и введите ответ в одну строку без пробелов.

my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

display(my_array, my_array[1:4, 1:4])




array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [363]:
# Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов
# полученного массива. Ответ округлите до трёх цифр после запятой.

my_sin = np.sin(my_array)
round(np.sum(my_sin), 3)


-0.058

In [366]:
# Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.
# Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

my_sin[1:4, 1:4] = 1
round(np.sum(my_sin), 3)


7.572

In [373]:
# Преобразуйте первые четыре столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов
# первого столбца получившегося массива? Ответ округлите до трёх заков после точки-разделителя. Используйте преобразованный в предыдущем задании массив my_sin.
round(np.sum(np.reshape(my_sin[:, :4], (10, 2))[:, 0]), 3)


2.406

In [384]:
# Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.
bigdata = np.array([
    x*x for x in range(100, 1000, 1)
    if x%2
])
bigdata


array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

In [385]:
# Чему равна медиана массива bigdata?
np.median(bigdata)


302501.0

In [386]:
# Чему равно стандартное отклонение для массива bigdata? Ответ округлите до целых:
round(np.std(bigdata))


292095

In [388]:
# Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами?
# Введите полученный ответ без изменений и округлений.
even_index = bigdata[::2]
odd_index = bigdata[1::2]
np.corrcoef(even_index, odd_index)



array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])