In [2]:
import numpy as np

In [3]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [4]:
A

array([[ 9,  6,  7],
       [10,  5,  8],
       [10,  5, 11]])

In [5]:
B

array([[ 2,  0,  3],
       [ 1, -1,  3],
       [-2,  2,  2]])

In [6]:
# Поэлементное умножение
A*B

array([[ 18,   0,  21],
       [ 10,  -5,  24],
       [-20,  10,  22]])

In [7]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[10  8 59]
 [ 9 11 61]
 [ 3 17 67]]


In [8]:
# Матричное умножение
np.dot(A,B)

array([[10,  8, 59],
       [ 9, 11, 61],
       [ 3, 17, 67]])

In [9]:
# Матричное умножение
A@B

array([[10,  8, 59],
       [ 9, 11, 61],
       [ 3, 17, 67]])

In [10]:
# Порядок умножения AB != BA
B@A

array([[48, 27, 47],
       [29, 16, 32],
       [22,  8, 24]])

In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[11  5 10  9  9]
 [11  9  8  6  9]
 [ 6  5  6 10  8]]
B:
 [[ 0  1]
 [ 3 -1]
 [-1  2]
 [-2 -2]
 [-1  3]]


In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-22,  35],
       [ -2,  33],
       [-19,  17]])

In [13]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [14]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [15]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 0 -2  2 -3]
 [-1 -3 -2 -2]
 [ 3  3  0 -3]
 [ 2  1 -1 -1]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 0 -4  0  3]
 [-1 -6  0  2]
 [ 3  6  0  3]
 [ 2  2  0  1]]
DA:
 [[ 0 -2  2 -3]
 [-2 -6 -4 -4]
 [ 0  0  0  0]
 [-2 -1  1  1]]


In [16]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [17]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [18]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [19]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [20]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [21]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [22]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])